Change the password `test` to `password` (#301)
The minimum password length is 8 characters in Neo4j, and the bash commands given in this documentation will fail since it uses `test`as password. This error message will be found in the log if test is used and the container will not start

```bash
➜  logs docker logs testneo4j
Invalid value for password. The minimum password length is 8 characters.
If Neo4j fails to start, you can:
1) Use a stronger password.
2) Set configuration dbms.security.auth_minimum_password_length to override the minimum password length requirement.
3) Set environment variable NEO4J_dbms_security_auth__minimum__password__length to override the minimum password length requirement.
java.lang.IllegalArgumentException: A password must be at least 8 characters.
	at org.neo4j.commandline.admin.security.SetInitialPasswordCommand.validatePassword(SetInitialPasswordCommand.java:114)
	at org.neo4j.commandline.admin.security.SetInitialPasswordCommand.execute(SetInitialPasswordCommand.java:71)
	at org.neo4j.cli.AbstractCommand.call(AbstractCommand.java:92)
	at org.neo4j.cli.AbstractCommand.call(AbstractCommand.java:37)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at org.neo4j.cli.AdminTool.execute(AdminTool.java:91)
	at org.neo4j.cli.AdminTool.main(AdminTool.java:79)
```
Therefore the password `test` is changed to `password` instead.